### ISSUE TITLE
Where to catch Error: Please pass a valid aggregate id!

### ISSUE THREAD

**Issue by bikerp** [adrai/node-cqrs-domain#147]
Hi,
 I use Promise to handle command:
```
function handleCommand(cmd) {
    return new Promise((resolve, reject) => {
        domain.handle(cmd, err => {
            if (err) {
                reject(err);
            }
            resolve();
        });
    });
}
```
However the problem is when `Error: Please pass a valid aggregate id! ` occurs then the whole process exits and the callback function is not called.
Is this a bug or I'm doing it wrong way?

Thanks

**Comment by adrai** [comment]
try like this:

```javascript
function handleCommand(cmd) {
    return new Promise((resolve, reject) => {
        try {
          domain.handle(cmd, err => {
              if (err) {
                  reject(err);
              }
              resolve();
          });
        } catch (e) { reject(e); }
    });
}
```

**Comment by nanov** [comment]
Just a small addition so you won't resolve an already rejected promise:

```js
function handleCommand(cmd) {
  return new Promise((resolve, reject) => {
    try {
      domain.handle(cmd, (err) => {
        if (err)
          return reject(err);
        resolve();
      });
     } catch (e) { reject(e) }
  });
}
```

note the return statement on the first reject.

**Comment by adrai** [comment]
right, didn’t see it

**Comment by bikerp** [comment]
Hi @adrai,
thanks for the feedback. I tried the try/catch but even this didn't help.

**Comment by nanov** [comment]
@bikerp This is rather strange, could you post the stack trace of the error?

**Comment by bikerp** [comment]
```
Error: Please pass a valid aggregate id!

    at DefaultCommandHandler.getNextCommandInQueue (C:\Users\bikerp\projects\test\src\\commands\node_modules\cqrs-domain\lib\defaultCommandHandler.js:112:17)
    at _handle (C:\Users\bikerp\projects\test\src\\commands\node_modules\cqrs-domain\lib\defaultCommandHandler.js:1133:27)
    at DefaultCommandHandler.handle (C:\Users\bikerp\projects\test\src\\commands\node_modules\cqrs-domain\lib\defaultCommandHandler.js:1163:14)
    at CommandDispatcher.dispatch (C:\Users\bikerp\projects\test\src\\commands\node_modules\cqrs-domain\lib\commandDispatcher.js:119:29)
    at C:\Users\bikerp\projects\test\src\\commands\node_modules\cqrs-domain\lib\domain.js:670:30
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by nanov** [comment]
Ok, i saw where the problem is. Will submit a fix!

**Comment by nanov** [comment]
Fixed in v2.14.73.

**Comment by adrai** [comment]
good catch

**Comment by nanov** [comment]
@bikerp Could you confirm that solves your issue? So we could close it on our side?

**Comment by bikerp** [comment]
@adrai Good job. It works. Even without the rty/catch. Thanks for the quick fix
